configuration:
  logging:
    level: info
  sdm:
    cache:
      enabled: true
      path: /cache
  env:
    version:
      image: 'atomist/version-goal:0.1.0-master.20191108121808'

---

immaterial:

  test:
  - not:
      is_material_change:
        files:
        - pom.xml
        - package.json
        extensions:
        - ts
        - js
        - java
        - html
        glob_patterns:
        - '**/Dockerfile'

  goals: lock
