configuration:
  logging:
    level: info
  sdm:
    cache:
      enabled: true
      path: /cache

---

immaterial:

  test:
  - not:
      is_material_change:
        files:
        - pom.xml
        - package.json
        extensions:
        - ts
        - js
        - java
        - html
        patterns:
        - '**/Dockerfile'

  goals: lock
