configuration:
  logging:
    level: info
  sdm:
    cache:
      enabled: true
      #path: /tmp/cache
      path: /cache
    goal:
      timeout: 1200000
      docker:
        registry: atomistplayground
        provider: atomist
  env:
    version\Ugoal\Uimage: 'git://atomist/version-goal@a8c0ea2'

---

immaterial:

  test:
  - not:
      is\Umaterial\Uchange:
        files:
        - pom.xml
        - package.json
        extensions:
        - ts
        - js
        - java
        - html
        patterns:
        - '**/Dockerfile'

  goals: lock
