configuration:
  name: "@atomist/demo-sdm"
  sdm:
    cache:
      enabled: true
      path: /cache

---

immaterial:

  test:
  - is_material_change:
      files:
      - pom.xml
      - package.json
      extensions:
      - ts
      - js
      - java
      - html
      patterns:
      - '**/Dockerfile'

  goals: immaterial
